"""
Data models for translation engine results and statistics.
"""
from dataclasses import dataclass, field
from enum import IntEnum
from pathlib import Path
from typing import Any, Dict, List, Optional


class ValidationDecision(IntEnum):
    """
    Decision outcome from validation.

    Values are ordered by severity:
    - ACCEPT (0): Translation is acceptable, no retry needed
    - RETRY (1): Translation has issues but may improve with retry
    - REJECT (2): Translation has critical errors, should not be used
    """
    ACCEPT = 0
    RETRY = 1
    REJECT = 2


@dataclass
class TranslationStats:
    """Statistics for a translation operation."""

    total_segments: int = 0
    tm_hits: int = 0  # Segments found in TM
    l1_hits: int = 0  # L1 cache hits
    l2_hits: int = 0  # L2 persistent hits
    l3_hits: int = 0  # L3 semantic hits
    translated_segments: int = 0  # New translations via model
    skipped_segments: int = 0  # Skipped (excluded by rules)
    duration_seconds: float = 0.0
    words_translated: int = 0  # Approximate word count
    model_used: Optional[str] = None

    # Token tracking (TEL-04 integration)
    tokens_input: int = 0  # Tokens sent to model for translation
    tokens_output: int = 0  # Tokens generated by model
    tokens_cached: int = 0  # Estimated tokens saved via TM hits
    tokens_total: int = 0  # Total tokens processed (cached + translated)

    # File operation tracking (TEL-04 integration)
    md_files_added: int = 0  # New .md files created
    md_files_updated: int = 0  # Existing .md files overwritten
    bytes_written_md: int = 0  # Total bytes written to .md files
    tm_entries_stored: int = 0  # TM entries stored (JSON-like)
    files_translated: int = 0  # Files completed successfully (TEL-05-A)
    files_generated: int = 0  # Output files produced across languages (TEL-05-A)

    # Validation metrics (INF-03: Post-translation validation tracking)
    validation_passed: bool = False  # True if validation passed without errors
    validation_failed: bool = False  # True if validation failed (errors detected)
    validation_retried: int = 0  # Number of retry attempts made
    validation_decision: str = ""  # Final decision: "ACCEPT", "RETRY", "REJECT"

    # Issue counts (INF-03: Validation issue tracking)
    validation_errors: int = 0  # Number of error-level issues
    validation_warnings: int = 0  # Number of warning-level issues
    validation_info: int = 0  # Number of info-level issues

    # Timing (INF-03: Performance tracking)
    validation_duration_ms: float = 0.0  # Time spent in validation
    retry_duration_ms: float = 0.0  # Total time spent on retry attempts

    # AST-based translation metrics
    ast_translation_enabled: bool = False  # True if AST-based translation was used
    ast_units_extracted: int = 0  # Total TextUnits extracted from AST
    ast_units_translatable: int = 0  # TextUnits that needed translation
    ast_units_protected: int = 0  # TextUnits marked as do_not_translate
    ast_batch_calls: int = 0  # Number of batch translation calls
    ast_individual_fallbacks: int = 0  # Number of fallbacks to individual translation

    @property
    def tm_hit_rate(self) -> float:
        """Calculate TM hit rate."""
        if self.total_segments == 0:
            return 0.0
        return self.tm_hits / self.total_segments

    @property
    def token_cache_rate(self) -> float:
        """Calculate percentage of tokens served from cache."""
        if self.tokens_total == 0:
            return 0.0
        return self.tokens_cached / self.tokens_total

    def __str__(self) -> str:
        """Human-readable summary."""
        base_stats = (
            f"TranslationStats("
            f"total={self.total_segments}, "
            f"tm_hits={self.tm_hits} ({self.tm_hit_rate:.1%}), "
            f"new={self.translated_segments}, "
            f"duration={self.duration_seconds:.2f}s)"
        )
        if self.tokens_total > 0:
            base_stats += (
                f" [tokens: {self.tokens_total} total, "
                f"{self.tokens_cached} cached ({self.token_cache_rate:.1%})]"
            )
        return base_stats


@dataclass
class TranslationResult:
    """Result of translating a single file."""

    success: bool
    file_path: Path
    outputs: Dict[str, Path] = field(default_factory=dict)  # lang -> output path
    stats: TranslationStats = field(default_factory=TranslationStats)
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    validation_result: Optional["ValidationResult"] = None  # Validation result if validation enabled

    # Decision state (INF-03: Validation decision tracking)
    validation_decision: Optional[ValidationDecision] = None  # Final validation decision
    decision_reason: Optional[str] = None  # Human-readable reason for the decision
    retry_attempts: int = 0  # Number of retry attempts made
    retry_history: List[Dict[str, Any]] = field(default_factory=list)  # History of retry attempts

    # VA-03: Post-translation verification result
    verification_result: Optional[Any] = None  # VerificationResult from verification agent

    # RES-05: Skip tracking for existing outputs
    skipped_langs: List[str] = field(default_factory=list)  # Languages skipped due to existing output
    skip_reasons: Dict[str, str] = field(default_factory=dict)  # {lang: reason} for skipped languages

    def __str__(self) -> str:
        """Human-readable summary."""
        status = "SUCCESS" if self.success else "FAILED"
        error_info = f", {len(self.errors)} errors" if self.errors else ""
        return f"{status}: {self.file_path}{error_info} - {self.stats}"


@dataclass
class DirectoryResult:
    """Result of translating multiple files in a directory."""

    success: bool
    directory: Path
    file_results: List[TranslationResult] = field(default_factory=list)
    total_files: int = 0
    successful_files: int = 0
    failed_files: int = 0
    duration_seconds: float = 0.0

    @property
    def aggregate_stats(self) -> TranslationStats:
        """Aggregate statistics across all files."""
        agg = TranslationStats()
        for result in self.file_results:
            agg.total_segments += result.stats.total_segments
            agg.tm_hits += result.stats.tm_hits
            agg.l1_hits += result.stats.l1_hits
            agg.l2_hits += result.stats.l2_hits
            agg.l3_hits += result.stats.l3_hits
            agg.translated_segments += result.stats.translated_segments
            agg.skipped_segments += result.stats.skipped_segments
            agg.words_translated += result.stats.words_translated
            agg.files_translated += result.stats.files_translated
            agg.files_generated += result.stats.files_generated

            # Aggregate validation metrics (INF-03)
            if result.stats.validation_passed:
                agg.validation_passed = True
            if result.stats.validation_failed:
                agg.validation_failed = True
            agg.validation_retried += result.stats.validation_retried
            agg.validation_errors += result.stats.validation_errors
            agg.validation_warnings += result.stats.validation_warnings
            agg.validation_info += result.stats.validation_info
            agg.validation_duration_ms += result.stats.validation_duration_ms
            agg.retry_duration_ms += result.stats.retry_duration_ms

            # Aggregate AST translation metrics
            if result.stats.ast_translation_enabled:
                agg.ast_translation_enabled = True
            agg.ast_units_extracted += result.stats.ast_units_extracted
            agg.ast_units_translatable += result.stats.ast_units_translatable
            agg.ast_units_protected += result.stats.ast_units_protected
            agg.ast_batch_calls += result.stats.ast_batch_calls
            agg.ast_individual_fallbacks += result.stats.ast_individual_fallbacks

        agg.duration_seconds = self.duration_seconds
        return agg

    def __str__(self) -> str:
        """Human-readable summary."""
        status = "SUCCESS" if self.success else "PARTIAL/FAILED"
        return (
            f"{status}: {self.directory} - "
            f"{self.successful_files}/{self.total_files} files, "
            f"{self.aggregate_stats}"
        )


@dataclass
class ValidationIssue:
    """A single validation issue found."""

    severity: str  # "error", "warning", "info"
    rule: str  # Name of validation rule
    message: str  # Human-readable description
    location: Optional[str] = None  # File path or segment ID

    def __str__(self) -> str:
        """Human-readable representation."""
        loc = f" at {self.location}" if self.location else ""
        return f"[{self.severity.upper()}] {self.rule}: {self.message}{loc}"


@dataclass
class ValidationResult:
    """Result of validation."""

    valid: bool  # True if no errors
    issues: List[ValidationIssue] = field(default_factory=list)

    @property
    def errors(self) -> List[ValidationIssue]:
        """Get only errors."""
        return [i for i in self.issues if i.severity == "error"]

    @property
    def warnings(self) -> List[ValidationIssue]:
        """Get only warnings."""
        return [i for i in self.issues if i.severity == "warning"]

    @property
    def info(self) -> List[ValidationIssue]:
        """Get only info messages."""
        return [i for i in self.issues if i.severity == "info"]

    def __str__(self) -> str:
        """Human-readable summary."""
        status = "VALID" if self.valid else "INVALID"
        counts = f"{len(self.errors)} errors, {len(self.warnings)} warnings"
        return f"{status}: {counts}"


@dataclass
class LanguageProgress:
    """
    Progress tracking for a single language.

    T304: Multi-language progress tracking (federated-splashing-panda).
    """
    language_code: str
    total_texts: int = 0
    completed_texts: int = 0
    success: bool = False
    error: Optional[str] = None

    @property
    def progress_percentage(self) -> float:
        """Calculate progress percentage (0.0 to 100.0)."""
        if self.total_texts == 0:
            return 100.0
        return (self.completed_texts / self.total_texts) * 100.0


@dataclass
class MultiLanguageProgress:
    """
    Aggregate progress tracking for multi-language processing.

    T304: Multi-language progress tracking (federated-splashing-panda).
    """
    languages: Dict[str, LanguageProgress] = field(default_factory=dict)
    mode: str = "serial"  # serial, parallel, roundrobin
    current_round: int = 0

    @property
    def total_languages(self) -> int:
        """Total number of languages."""
        return len(self.languages)

    @property
    def completed_languages(self) -> int:
        """Number of completed languages."""
        return sum(1 for lang in self.languages.values() if lang.completed_texts >= lang.total_texts)

    @property
    def overall_progress_percentage(self) -> float:
        """Calculate overall progress percentage."""
        if not self.languages:
            return 100.0
        total_texts = sum(lang.total_texts for lang in self.languages.values())
        completed_texts = sum(lang.completed_texts for lang in self.languages.values())
        if total_texts == 0:
            return 100.0
        return (completed_texts / total_texts) * 100.0
